version: '3.4'

services:
  db:
    image: gerenciador-jogos-webapi-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo 
      MYSQL_ROOT_PASSWORD: docker  
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: GerenciadorJogos
    ports:
      - 3308:3306
    networks:
      - gerenciador-jogos-network  
  gerenciador-jogos-webapi:
    image: gerenciador-jogos-webapi
    build:
      context: .
      dockerfile: GerenciadorJogos.WebApi/Dockerfile
    environment:
      TZ: America/Sao_Paulo 
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 51136:80
    depends_on:
      - db
    networks:
      - gerenciador-jogos-network
  front:
    image: gerenciador-jogos-webapi-front
    build:
      context: .
      dockerfile: front/Dockerfile
    environment:
      TZ: America/Sao_Paulo 
      SITE_URL: http://localhost:51137/
      SITE_BANCO: meu_site
    ports:
      - 51137:80
    depends_on:
      - gerenciador-jogos-webapi
    networks:
      - gerenciador-jogos-network  
networks:
  gerenciador-jogos-network:
    driver: bridge
